### ISSUE TITLE
Audio Nodes: Audio Params

### ISSUE THREAD

**Issue by zauner** [zauner/vvvv.js#21]
As follow up to this pull request https://github.com/zauner/vvvv.js/pull/20 

I am at the moment experimenting with pin compatibility, so a pin type can be compatible to multiple other pin types. In this case: VVVV.PinTypes.AudioParam could receive incoming connections from VVVV.PinTypes.WebAudio and VVVV.PinTypes.Value. (or String input pins could also get values from Value pins, to completely break compatibily with classic VVVV ;) )

The other (much quicker) solution would be an option @artofmus suggested: converter nodes from audio signal to audio param, and value to audio param. Like AsAudioParam (WebAudio) and AsAudioParam (Value). This of course would mean that all params would always need one of those two nodes as input

**Comment by geloescht** [comment]
I kind of like option two. Audio params are as far as I know always inputs (except for some non-standard browser implementations). So maybe we can get rid of the conversion for audio streams and only provide AsAudioParam (Value)? We'd have to prevent feeding values into real audio input pins, though.
In my opinion option one would be nice only if doable without breaking VVVV compatibility.

**Comment by zauner** [comment]
You said it, the normal Audio Signal pins can't be confused with the Param pins. That's why i think it's inevitable to have this VVVV.PinTypes.AudioParam. Just for pretending it's something different, while it's actually either a float, or an api node.

The AsAudioParam nodes would actually do *nothing* but feed the value from one pin type to the other, without doing any conversion.

One thing to consider in any case is, what happens if such a pin gets disconnected. E.g. the Oscillator has a default frequency of 440 ... i change the value to 200 ... i (somehow) connect another Oscillator to the frequency pin, and things get all FMy. Then i disconnect the pin again -- what should happen? Should the value get back to 200, or to 440 or to 'the current modulator value' (if it's even possible to retreive this) ?

**Comment by geloescht** [comment]
Actually, what happens inside API nodes is even more complicated. The value gets _modulated_ by any audio stream feeding into a parameter. See this part of the spec: http://webaudio.github.io/web-audio-api/#computation-of-value
So maybe we have to provide two input pins per audio param. One for the base value (pin type Value) and modulation (pin type WebAudio).

**Comment by zauner** [comment]
ok so if i do

    myOsc.freq = 300;
    otherOsc.connect(myOsc.freq)

300 and the modulator signal are added up? Well then the decision is easy, and it's two pins per param, right?

@artofmus suggested this as well, I initially considered this impractical. But it might be the right thing.

**Comment by geloescht** [comment]
In theory yes. I will try and implement that. Although it could get confusing whith some nodes that have a high number of params, such as BiquadFilterNode. But when it is implemented we can worry about that.

**Comment by geloescht** [comment]
Implemented in a06d946a31a88cea2f3efd1e9fe316b. FM synthesis is sweet. DynamicsCompressor (HTML5 Audio) gets pretty large with 13 input pins (should be 11 really, browsers incorrectly implement DynamicsCompressorNode.reduction as an AudioParam).

**Comment by zauner** [comment]
That's really fun to play with. I wish I had a clue about harmonics, though :)

Merged it into master.

**Comment by artofmus** [comment]
Looked, looks great) I would like to see at some sort of mixer, because without it, nothing really can be done. Although if you implement the spreads concept  it need not be, possible to make the nodes something like vec2d(join) vec2d(split) stallone etc.,and it would, I think, a very innovative and correctly.) More interesting to know whether you will add ScriptProcessorNode? Would have been the height of perfection if you make something like shader code editor only for audio processing. And a little lacking ReverbNode full of happiness)

**Comment by geloescht** [comment]
ScriptProcessorNode is deprecated in favor of AudioWorker, which, sadly, isn't implemented yet by any browser vendor. If we add a script processor node now we should be extra careful to make it portable to AudioWorker.
Reverb is possible using Convolver (HTML5 Audio). You'll need an impulse response sample - you can download one for free from http://www.openairlib.net/ and load it via FileAudioBuffer (HTML5 Audio).

**Comment by artofmus** [comment]
oops) seemed to me that there is a separate ReverbNode) About AudioWorker I missed it, I'll know.
