### ISSUE TITLE
Audio Nodes: Spreadability

### ISSUE THREAD

**Issue by zauner** [zauner/vvvv.js#22]
As follow up to this pull request #20

I guess the "correct way of spreading" would be to indeed create multiple api nodes in a vvvv.js node, and pass those on as a spread.

Meaning, a Delay with two signals as input, and only one value as time input, should create two Delai api nodes, and output a spread of 2.

The other way around, a Delay node with one input signal, and 2 values as time input, should also create two Delay api nodes. At least in theory, as I don't know if it's possible to connect one signal to multiple other nodes.

At least I think this would be how a user would expect it to work, don't you think @geloescht and @artofmus?

**Comment by geloescht** [comment]
Yes, indeed I think this is the correct way. The Web Audio API also supports multiple audio channels per node, but a parameter is always shared by all channels. Plus some nodes support only a fixed number of channels.
The Web Audio API is perfectly capable of feeding one audio stream to multiple nodes.
I think it should be fairly straight-forward to implement:
- apiNode should be an array apiNodes with at least one entry
- createAPINode() should be renamed to createAPINodes() and should take into account getMaxInputSliceCount()
- createAPINodes() needs to handle changes of getMaxInputSliceCount()
- the rest is just a matter of looping over slices

**Comment by geloescht** [comment]
OK, I took a look at the VVVV.Audio pack (VAudio nodes). It implements channels as spreads.
However it is unclear to me what it does exactly when the input stream is not stereo. The FFT node seems to ignore the first channel or downmix it with the second, outputting a spread of 512*(input slices - 1) slices. Resample crashes VVVV on my computer. Most processing seems to be based on VST plugins, which I can't test currently.
As we cannot hope to use VST plugins in the browser I'd opt for not trying to be compatible with VVVV.Audio and do our own thing. Which means the number of channels is a property of the audio stream independent of the slice count. For splitting and joining of channels the Web Audio API provides ChannelSplitterNode and ChannelMergerNode.
The other option would be doing a mixture of both where as many API nodes per VVVV node are created as needed depending on the slice count of different inputs.

**Comment by zauner** [comment]
I also think that we don't need to be compatible with VAudio here, as the underlying concepts (and possibilities) seem to be rather different.

the `apiNodes = []` way you suggested above seems reasonable to me. I would do it that way. Hard to tell how crazy things get with high slice counts, though. But I'm sure with nodes behaving like this, you can get the most fun out of it.

**Comment by artofmus** [comment]
And I, too, for  abandon the analogy with VAudio I think that the spreads should not depend on the number of channels, and should mean just a lot of nodes with different parameters, for example, if a parameter in the oscillator node frequency, we aim spread [200, 300, 400, 500] this means that we create four oscillator with frequencies 200 300 400 and 500 hertz, then if we aim at delay node with time parameters [1, 2, 3, 4] seconds that mean oscillator with 200 hz is delayed by 1 sec., 300 by 2, etc. . if delay node with time parameters [1, 2], then oscillator with 200 hz by  1 sec, 300 by 2, 400 back by 1 and 500 by 2, and so all in spreads logic .

**Comment by artofmus** [comment]
Are there any success with spreads?

**Comment by geloescht** [comment]
I made some progress at spreading, see geloescht/vvvv.js@13bb3ffb6d (audio branch). A few nodes still need conversion and all of it needs a lot of testing. The strange names like apiMultiNode are there so I can use search to see if I missed something that needs to be made spreadable. When the conversion is done I'll remove the compatibility variable WebAudioNode.apiNode and rename apiMultiNode etc. to apiNodes.

**Comment by artofmus** [comment]
I have no sound ... While in firefox in Developer Tools everything looks as it should...

**Comment by geloescht** [comment]
Can you please retry with the newest audio branch from geloescht/vvvv.js and send me your v4p patch if it still does not work?

**Comment by artofmus** [comment]
Yes, still does not work( The patch is very simple, I connect oscillator to destination and can not hear any sound. With previous versions of everything is fine.

**Comment by geloescht** [comment]
Oh, I see what I did there. Fixed in geloescht/vvvv.js@6aaf19d. BTW, try connecting a LinearSpread to the frequency input of an oscillator. Results in some funky sounds ;)

**Comment by artofmus** [comment]
Super! Vary cool) I think this will be the beginning of a new direction in music - spreadmusic) In Firefox free why do not work waveshaper and convolver nodes. In chrome - ok.

**Comment by zauner** [comment]
amazing :) now this calls for a HarmonicSpread node, right? :)

**Comment by geloescht** [comment]
@zauner: Can be done with a Multiply and an I node, as harmonics are just integer multiples of the fundamental frequency. In most synthesizers you also get a nice mixer for the individual volume of each harmonic, that could be done with Gain and an IOBox (at least in classic VVVV, I don't think we have sliders yet in vvvv.js).

@artofmus: Waveshaper, I don't know why, could you send me an example please? It needs a very specific kind of spread on its Curve input, maybe that's the problem. As for Convolver, the problem could actually be in FileAudioBuffer. Firefox refuses to load certain .wav files: https://bugzilla.mozilla.org/show_bug.cgi?id=864780 Could you look into the console log to see if there is any error about decoding or other media related stuff?

**Comment by zauner** [comment]
I just reintegrated this into master.
