### ISSUE TITLE
Exception in Firefox when changing IOBox value in browser editor

### ISSUE THREAD

**Issue by geloescht** [zauner/vvvv.js#26]
When I change a value in an IOBox via right-click I get the following exception in Fx 36:
TypeError: win.window.document.exitPointerLock is not a function
Also, the IOBox moves with the cursor until I click somewhere inside the editor window.
The pointer lock API seems kinda unmaintained on Firefox. Maybe this is a prefixing issue?

**Comment by zauner** [comment]
Just saw you already fixed that, thanks.
