### ISSUE TITLE
No links are created when loading a patch with node requirements

### ISSUE THREAD

**Issue by geloescht** [zauner/vvvv.js#29]
Steps to reproduce:
- create a patch with the BeatDetector node
- save & reload it
Result (at least on my computer both on Chrome and Firefox)
- Patch does not execute

By debugging I suspect the problem lies in the beatdetektor library not loading in time before BeatDetecor.evaluate calls the BeatDetektor constructor, but I am not sure about that. I cannot see any exceptions being thrown, however if I use the debugger to step through the script  for a few lines after the BeatDetector constructor has executed, everything works fine.

**Comment by geloescht** [comment]
OK, I investigated this problem further an pinned it down to line 1465 in vvvv.core.js:
`if (this.resourcesPending===0)
    updateLinks(xml);`
So creating links is skipped if there are unloaded requirements, but the links don't get created later on either.

**Comment by zauner** [comment]
confirmed, will have a look at it.
